### PR TITLE
PCF-4 eggd picardqc v1.1.0

### PR DESCRIPTION
**Pull request by Aisha-D**
This app uses picard to run calculate different metrics. CollectRnaSeqMetrics is a QC metrics required for RNA samples. This function has been added to the script. An example of the command can be found here: https://cuhbioinformatics.atlassian.net/wiki/spaces/PANCANCER/pages/2820472856/CollectRnaSeqMetrics+Picard

Changes:
- Add new input for the tool to convert genome gtf to reflat
- New CollectRnaSeqMetrics function
- Reshuffle the create_interval_file to only be run when the old functions (CollectMultipleMetrics, CollectHsMetrics,CollectTargetedPcrMetrics) are set as true

Test jobs with new code:
- RNA sample - https://platform.dnanexus.com/projects/GPyxpxj4GYVb15ggYF9jPV5z/monitor/job/GQ087k04GYVvB85xJ8v6zPK2
- DNA sample - https://platform.dnanexus.com/projects/GPyxpxj4GYVb15ggYF9jPV5z/monitor/job/GQ0B6604GYVXyzYjG1Kx0fKk

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_picardqc/6)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_picardqc/6)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

___
*[`dxapp.json` line 44 at r1](https://reviewable.io/reviews/eastgenomics/eggd_picardqc/6#-NPYLqF9DjO1Wi1sTVc-:-NPYLqF9DjO1Wi1sTVc0:b-mo9tg) ([raw file](https://github.com/eastgenomics/eggd_picardqc/blob/99dcacd09db7085db70c41f4b9d6ff12dcab6703/dxapp.json#L44)):*
> ```JSON
>       "name": "GtftoRefflat_jar",
>       "label": "GTF to Ref flat jar",
>       "help": "Choose manufacturer's bed file (for the enrichment kit) whose coordinates will be used to calculate the selection metrics.",
> ```

Help text from bedfile input - leftover from copy/paste?



_Code quote:_
```JSON
"Choose manufacturer's bed file (for the enrichment kit) whose coordinates will be used to calculate the selection metrics."
```

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_picardqc/6)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @Aisha-D)

___
*[`src/code.sh` line 71 at r1](https://reviewable.io/reviews/eastgenomics/eggd_picardqc/6#-NPYMS8lBx7dA5O_Ak4U:-NPYMS8lBx7dA5O_Ak4V:b5qp3qb) ([raw file](https://github.com/eastgenomics/eggd_picardqc/blob/99dcacd09db7085db70c41f4b9d6ff12dcab6703/src/code.sh#L71)):*
> ```Shell
> 	echo "Gtf to Refflat"
> 	# find genome file
> 	ref_genome_gtf=$(find . -type f -name \*annot.gtf)
> ```

Will these gtfs always follow this naming pattern?



_Code quote:_
```Shell
-name \*annot.gtf
```
___
*[`src/code.sh` line 133 at r1](https://reviewable.io/reviews/eastgenomics/eggd_picardqc/6#-NPYO4Cx6-i9Iugi_mIq:-NPYO4Cx6-i9Iugi_mIr:bkzqth3) ([raw file](https://github.com/eastgenomics/eggd_picardqc/blob/99dcacd09db7085db70c41f4b9d6ff12dcab6703/src/code.sh#L133)):*
> ```Shell
> # Call Picard CollectTargetedPcrMetrics
> collect_targeted_pcr_metrics
> fi
> ```

Perhaps this would be cleaner/DRYer:



_Suggestion:_
```Shell
# Create the interval file if required
[ "$run_CollectMultipleMetrics" == true ] || [ "$run_CollectHsMetrics" == true ] || [ "$run_CollectTargetedPcrMetrics" == true ]; then
create_interval_file

# if run_CollectMultipleMetrics is true
if [[ "$run_CollectMultipleMetrics" == true ]]; then
# Call Picard CollectMultipleMetrics
collect_multiple_metrics
fi

# if run_CollectHsMetrics is true
if [[ "$run_CollectHsMetrics" == true ]]; then
# Call Picard CollectHSMetrics
collect_hs_metrics
fi

# if run_CollectTargetedPcrMetrics is true
if [[ "$run_CollectTargetedPcrMetrics" == true ]]; then
# Call Picard CollectTargetedPcrMetrics
collect_targeted_pcr_metrics
fi
```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_picardqc/6)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @mattgarner)

___
*[`dxapp.json` line 44 at r1](https://reviewable.io/reviews/eastgenomics/eggd_picardqc/6#-NPYLqF9DjO1Wi1sTVc-:-NPYVVSZ5R1Qt1TM-txv:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_picardqc/blob/99dcacd09db7085db70c41f4b9d6ff12dcab6703/dxapp.json#L44)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Help text from bedfile input - leftover from copy/paste?
</blockquote></details>

Done.
___
*[`src/code.sh` line 71 at r1](https://reviewable.io/reviews/eastgenomics/eggd_picardqc/6#-NPYMS8lBx7dA5O_Ak4U:-NPYVWQLDn0NvwbJrqNj:b-wg4hqv) ([raw file](https://github.com/eastgenomics/eggd_picardqc/blob/99dcacd09db7085db70c41f4b9d6ff12dcab6703/src/code.sh#L71)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Will these gtfs always follow this naming pattern?
</blockquote></details>

yes - this is actually a pitfall that needs to be mentioned in the readme that the RNA index is for CTAT only and follows this extension ending.
___
*[`src/code.sh` line 133 at r1](https://reviewable.io/reviews/eastgenomics/eggd_picardqc/6#-NPYO4Cx6-i9Iugi_mIq:-NPYVxG84S1SVGNyXlTJ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_picardqc/blob/99dcacd09db7085db70c41f4b9d6ff12dcab6703/src/code.sh#L133)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Perhaps this would be cleaner/DRYer:
</blockquote></details>

Done.

**Review by mattgarner — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_picardqc/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
