### PR TITLE
V1.2.0

### PR DESCRIPTION
**Pull request by spaul91**
PR to master branch containing all changes from dev->v1.2.0

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_picardqc/22)

## Summary by CodeRabbit

- **New Features**
	- Updated version to 1.2.0 for the `eggd_picard_QC` application.
	- Introduced new optional inputs: `vcf` for called variants and `dbsnp_vcf` for dbSNP variants.
	- Added a new boolean input `run_CollectVariantCallingMetrics` to control the execution of variant calling metrics calculations.

- **Bug Fixes**
	- Updated existing inputs `sorted_bam` and `fasta_index` to be optional, enhancing flexibility for users.

- **Improvements**
	- Enhanced error handling and input validation in the processing script for better usability and robustness.

### CODE REVIEW

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_picardqc/22)* status: all files reviewed, 11 unresolved discussions (waiting on @spaul91)

___
*[`src/code.sh` line 73 at r1](https://reviewable.io/reviews/eastgenomics/eggd_picardqc/22#-ODCJ7Wj7w-AzPr-AFUm:-ODCJ7Wk8dF_kC6aVNRF:b2uw8lt) ([raw file](https://github.com/eastgenomics/eggd_picardqc/blob/761741c9282ac400622c76a7310d6523e42327bb/src/code.sh#L73)):*
> ```Shell
> #   $4 - Java maximum heap size
> #
> # TODO: Investigate CollectSequencingArtifactMetrics - it errors out with TSO500 BAMs due to
> ```

can that be moved to a github issue? i must have missed that in the smaller PR

**Comment by spaul91** [comment]
*[`src/code.sh` line 73 at r1](https://reviewable.io/reviews/eastgenomics/eggd_picardqc/22#-ODCJ7Wj7w-AzPr-AFUm:-ODH2ZnXC6U4MHpton93:b7mkgbc) ([raw file](https://github.com/eastgenomics/eggd_picardqc/blob/761741c9282ac400622c76a7310d6523e42327bb/src/code.sh#L73)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

can that be moved to a github issue? i must have missed that in the smaller PR
</blockquote></details>

@coderabbitai[bot] can you open an issue for this please?

**Comment by spaul91** [comment]
*[`src/code.sh` line 73 at r1](https://reviewable.io/reviews/eastgenomics/eggd_picardqc/22#-ODCJ7Wj7w-AzPr-AFUm:-ODH2uIF0IZrZj-Axhvl:blugym1) ([raw file](https://github.com/eastgenomics/eggd_picardqc/blob/761741c9282ac400622c76a7310d6523e42327bb/src/code.sh#L73)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

@coderabbitai[bot] can you open an issue for this please?
</blockquote></details>

never mind. I'll open the issue

**Review by Yu-jinKim — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_picardqc/22)* status: all files reviewed, 11 unresolved discussions (waiting on @spaul91)

**Review by Yu-jinKim — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_picardqc/22)* status: all files reviewed, 10 unresolved discussions (waiting on @spaul91)

**Pull request merged**
